directeur:
    path:     /
    defaults: { _controller: "GestionBundle:Directeur:index" }

directeur_show:
    path:     /{id}/show
    defaults: { _controller: "GestionBundle:Directeur:show" }

directeur_new:
    path:     /new
    defaults: { _controller: "GestionBundle:Directeur:new" }

directeur_create:
    path:     /create
    defaults: { _controller: "GestionBundle:Directeur:create" }
    methods:  POST

directeur_edit:
    path:     /{id}/edit
    defaults: { _controller: "GestionBundle:Directeur:edit" }

directeur_update:
    path:     /{id}/update
    defaults: { _controller: "GestionBundle:Directeur:update" }
    methods:  [POST, PUT]

directeur_delete:
    path:     /{id}/delete
    defaults: { _controller: "GestionBundle:Directeur:delete" }
    methods:  [POST, DELETE]
