employe:
    path:     /
    defaults: { _controller: "GestionBundle:Employe:index" }

employe_show:
    path:     /{id}/show
    defaults: { _controller: "GestionBundle:Employe:show" }

employe_pdf:
    path:     /employe_pdf
    defaults: { _controller: "GestionBundle:Employe:employe_pdf" }

employe_new:
    path:     /new
    defaults: { _controller: "GestionBundle:Employe:new" }

employe_create:
    path:     /create
    defaults: { _controller: "GestionBundle:Employe:create" }
    methods:  POST

employe_edit:
    path:     /{id}/edit
    defaults: { _controller: "GestionBundle:Employe:edit" }

employe_update:
    path:     /{id}/update
    defaults: { _controller: "GestionBundle:Employe:update" }
    methods:  [POST, PUT]

employe_delete:
    path:     /{id}/delete
    defaults: { _controller: "GestionBundle:Employe:delete" }
    methods:  [POST, DELETE]
