fonction:
    path:     /
    defaults: { _controller: "GestionBundle:Fonction:index" }

fonction_show:
    path:     /{id}/show
    defaults: { _controller: "GestionBundle:Fonction:show" }

fonction_new:
    path:     /new
    defaults: { _controller: "GestionBundle:Fonction:new" }

fonction_create:
    path:     /create
    defaults: { _controller: "GestionBundle:Fonction:create" }
    methods:  POST

fonction_edit:
    path:     /{id}/edit
    defaults: { _controller: "GestionBundle:Fonction:edit" }

fonction_update:
    path:     /{id}/update
    defaults: { _controller: "GestionBundle:Fonction:update" }
    methods:  [POST, PUT]

fonction_delete:
    path:     /{id}/delete
    defaults: { _controller: "GestionBundle:Fonction:delete" }
    methods:  [POST, DELETE]
