mission:
    path:     /{idemp}/
    defaults: { _controller: "GestionBundle:Mission:index" }

mission_show:
    path:     /{id}/show
    defaults: { _controller: "GestionBundle:Mission:show" }

mission_pdf:
    path:     /{idemp}/{idmission}/mission_pdf
    defaults: { _controller: "GestionBundle:Mission:mission_pdf" }

mission_new:
    path:     /{idemp}/new
    defaults: { _controller: "GestionBundle:Mission:new" }

mission_create:
    path:     /{idemp}/create
    defaults: { _controller: "GestionBundle:Mission:create" }
    methods:  POST

mission_edit:
    path:     /{id}/edit
    defaults: { _controller: "GestionBundle:Mission:edit" }

mission_update:
    path:     /{id}/update
    defaults: { _controller: "GestionBundle:Mission:update" }
    methods:  [POST, PUT]

mission_delete:
    path:     /{id}/delete
    defaults: { _controller: "GestionBundle:Mission:delete" }
    methods:  [POST, DELETE]
