<?php

namespace Gestion\GestionBundle\Repository;

/**
 * BanqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BanqueRepository extends \Doctrine\ORM\EntityRepository
{
}
