<?php

namespace Gestion\GestionBundle\Repository;

/**
 * salairecompoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class salairecompoRepository extends \Doctrine\ORM\EntityRepository
{
}
