<?php

namespace Gestion\GestionBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DirecteurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DirecteurRepository extends EntityRepository
{
}
