<?php

namespace Gestion\GestionBundle\Entity;

/**
 * salairecompRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class salairecompRepository extends \Doctrine\ORM\EntityRepository
{
}
