services:
    app.image_type_extension:
        class: GestionBundle\Form\Extension\ImageTypeExtension
        tags:
            - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\FileType }
#    gestion.example:
#        class: Gestion\GestionBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
