categorieproduit:
    path:     /
    defaults: { _controller: "VentesBundle:CategorieProduit:index" }

categorieproduit_show:
    path:     /{id}/show
    defaults: { _controller: "VentesBundle:CategorieProduit:show" }

categorieproduit_new:
    path:     /new
    defaults: { _controller: "VentesBundle:CategorieProduit:new" }

categorieproduit_create:
    path:     /create
    defaults: { _controller: "VentesBundle:CategorieProduit:create" }
    methods:  POST

categorieproduit_edit:
    path:     /{id}/edit
    defaults: { _controller: "VentesBundle:CategorieProduit:edit" }

categorieproduit_update:
    path:     /{id}/update
    defaults: { _controller: "VentesBundle:CategorieProduit:update" }
    methods:  [POST, PUT]

categorieproduit_delete:
    path:     /{id}/delete
    defaults: { _controller: "VentesBundle:CategorieProduit:delete" }
    methods:  [POST, DELETE]
