members_account:
    resource: "@MembersBundle/Resources/config/routing/accountmember.yml"
    prefix:   /admin/account

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    prefix: /

fos_user_group:
    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
    prefix: /group