parameters:
    safric.form_manager.class: Members\MembersBundle\Services\ManagedForm

services:
#    members.example:
#        class: Members\MembersBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    fos_user.doctrine_registry:
        alias: doctrine

    safric.form_manager:
        class: %safric.form_manager.class% 
