<?php

namespace Proxies\__CG__\Ventes\VentesBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Facture extends \Ventes\VentesBundle\Entity\Facture implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Ventes\\VentesBundle\\Entity\\Facture' . "\0" . 'id', '' . "\0" . 'Ventes\\VentesBundle\\Entity\\Facture' . "\0" . 'numero', '' . "\0" . 'Ventes\\VentesBundle\\Entity\\Facture' . "\0" . 'reduction', '' . "\0" . 'Ventes\\VentesBundle\\Entity\\Facture' . "\0" . 'totalFacture', '' . "\0" . 'Ventes\\VentesBundle\\Entity\\Facture' . "\0" . 'remise', '' . "\0" . 'Ventes\\VentesBundle\\Entity\\Facture' . "\0" . 'tvafacture', '' . "\0" . 'Ventes\\VentesBundle\\Entity\\Facture' . "\0" . 'typeFacture', '' . "\0" . 'Ventes\\VentesBundle\\Entity\\Facture' . "\0" . 'dateFacture', '' . "\0" . 'Ventes\\VentesBundle\\Entity\\Facture' . "\0" . 'etat', '' . "\0" . 'Ventes\\VentesBundle\\Entity\\Facture' . "\0" . 'lastUpdate', '' . "\0" . 'Ventes\\VentesBundle\\Entity\\Facture' . "\0" . 'detailsProduits', '' . "\0" . 'Ventes\\VentesBundle\\Entity\\Facture' . "\0" . 'encaissement', '' . "\0" . 'Ventes\\VentesBundle\\Entity\\Facture' . "\0" . 'client', '' . "\0" . 'Ventes\\VentesBundle\\Entity\\Facture' . "\0" . 'utilisateur');
        }

        return array('__isInitialized__', '' . "\0" . 'Ventes\\VentesBundle\\Entity\\Facture' . "\0" . 'id', '' . "\0" . 'Ventes\\VentesBundle\\Entity\\Facture' . "\0" . 'numero', '' . "\0" . 'Ventes\\VentesBundle\\Entity\\Facture' . "\0" . 'reduction', '' . "\0" . 'Ventes\\VentesBundle\\Entity\\Facture' . "\0" . 'totalFacture', '' . "\0" . 'Ventes\\VentesBundle\\Entity\\Facture' . "\0" . 'remise', '' . "\0" . 'Ventes\\VentesBundle\\Entity\\Facture' . "\0" . 'tvafacture', '' . "\0" . 'Ventes\\VentesBundle\\Entity\\Facture' . "\0" . 'typeFacture', '' . "\0" . 'Ventes\\VentesBundle\\Entity\\Facture' . "\0" . 'dateFacture', '' . "\0" . 'Ventes\\VentesBundle\\Entity\\Facture' . "\0" . 'etat', '' . "\0" . 'Ventes\\VentesBundle\\Entity\\Facture' . "\0" . 'lastUpdate', '' . "\0" . 'Ventes\\VentesBundle\\Entity\\Facture' . "\0" . 'detailsProduits', '' . "\0" . 'Ventes\\VentesBundle\\Entity\\Facture' . "\0" . 'encaissement', '' . "\0" . 'Ventes\\VentesBundle\\Entity\\Facture' . "\0" . 'client', '' . "\0" . 'Ventes\\VentesBundle\\Entity\\Facture' . "\0" . 'utilisateur');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Facture $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumero($numero)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumero', array($numero));

        return parent::setNumero($numero);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumero()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumero', array());

        return parent::getNumero();
    }

    /**
     * {@inheritDoc}
     */
    public function setReduction($reduction)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReduction', array($reduction));

        return parent::setReduction($reduction);
    }

    /**
     * {@inheritDoc}
     */
    public function getReduction()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReduction', array());

        return parent::getReduction();
    }

    /**
     * {@inheritDoc}
     */
    public function setTotalFacture($totalFacture)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTotalFacture', array($totalFacture));

        return parent::setTotalFacture($totalFacture);
    }

    /**
     * {@inheritDoc}
     */
    public function getTotalFacture()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotalFacture', array());

        return parent::getTotalFacture();
    }

    /**
     * {@inheritDoc}
     */
    public function setRemise($remise)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRemise', array($remise));

        return parent::setRemise($remise);
    }

    /**
     * {@inheritDoc}
     */
    public function getRemise()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRemise', array());

        return parent::getRemise();
    }

    /**
     * {@inheritDoc}
     */
    public function setTvafacture($tvafacture)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTvafacture', array($tvafacture));

        return parent::setTvafacture($tvafacture);
    }

    /**
     * {@inheritDoc}
     */
    public function getTvafacture()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTvafacture', array());

        return parent::getTvafacture();
    }

    /**
     * {@inheritDoc}
     */
    public function setTypeFacture($typeFacture)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTypeFacture', array($typeFacture));

        return parent::setTypeFacture($typeFacture);
    }

    /**
     * {@inheritDoc}
     */
    public function getTypeFacture()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTypeFacture', array());

        return parent::getTypeFacture();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateFacture($dateFacture)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateFacture', array($dateFacture));

        return parent::setDateFacture($dateFacture);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateFacture()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateFacture', array());

        return parent::getDateFacture();
    }

    /**
     * {@inheritDoc}
     */
    public function setEtat($etat)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEtat', array($etat));

        return parent::setEtat($etat);
    }

    /**
     * {@inheritDoc}
     */
    public function getEtat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEtat', array());

        return parent::getEtat();
    }

    /**
     * {@inheritDoc}
     */
    public function setLastUpdate($lastUpdate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLastUpdate', array($lastUpdate));

        return parent::setLastUpdate($lastUpdate);
    }

    /**
     * {@inheritDoc}
     */
    public function getLastUpdate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLastUpdate', array());

        return parent::getLastUpdate();
    }

    /**
     * {@inheritDoc}
     */
    public function addDetailsProduit(\Ventes\VentesBundle\Entity\DetailsProduits $detailsProduits)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addDetailsProduit', array($detailsProduits));

        return parent::addDetailsProduit($detailsProduits);
    }

    /**
     * {@inheritDoc}
     */
    public function removeDetailsProduit(\Ventes\VentesBundle\Entity\DetailsProduits $detailsProduits)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeDetailsProduit', array($detailsProduits));

        return parent::removeDetailsProduit($detailsProduits);
    }

    /**
     * {@inheritDoc}
     */
    public function getDetailsProduits()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDetailsProduits', array());

        return parent::getDetailsProduits();
    }

    /**
     * {@inheritDoc}
     */
    public function addEncaissement(\Ventes\VentesBundle\Entity\Encaissement $encaissement)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addEncaissement', array($encaissement));

        return parent::addEncaissement($encaissement);
    }

    /**
     * {@inheritDoc}
     */
    public function removeEncaissement(\Ventes\VentesBundle\Entity\Encaissement $encaissement)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeEncaissement', array($encaissement));

        return parent::removeEncaissement($encaissement);
    }

    /**
     * {@inheritDoc}
     */
    public function getEncaissement()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEncaissement', array());

        return parent::getEncaissement();
    }

    /**
     * {@inheritDoc}
     */
    public function setClient(\Ventes\VentesBundle\Entity\Client $client)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClient', array($client));

        return parent::setClient($client);
    }

    /**
     * {@inheritDoc}
     */
    public function getClient()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClient', array());

        return parent::getClient();
    }

    /**
     * {@inheritDoc}
     */
    public function setUtilisateur(\Members\MembersBundle\Entity\AccountMember $utilisateur = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUtilisateur', array($utilisateur));

        return parent::setUtilisateur($utilisateur);
    }

    /**
     * {@inheritDoc}
     */
    public function getUtilisateur()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUtilisateur', array());

        return parent::getUtilisateur();
    }

}
