<?php

namespace Proxies\__CG__\Gestion\GestionBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Absence extends \Gestion\GestionBundle\Entity\Absence implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Gestion\\GestionBundle\\Entity\\Absence' . "\0" . 'id', '' . "\0" . 'Gestion\\GestionBundle\\Entity\\Absence' . "\0" . 'datedept', '' . "\0" . 'Gestion\\GestionBundle\\Entity\\Absence' . "\0" . 'dateretour', '' . "\0" . 'Gestion\\GestionBundle\\Entity\\Absence' . "\0" . 'employe', '' . "\0" . 'Gestion\\GestionBundle\\Entity\\Absence' . "\0" . 'destination', '' . "\0" . 'Gestion\\GestionBundle\\Entity\\Absence' . "\0" . 'motif');
        }

        return array('__isInitialized__', '' . "\0" . 'Gestion\\GestionBundle\\Entity\\Absence' . "\0" . 'id', '' . "\0" . 'Gestion\\GestionBundle\\Entity\\Absence' . "\0" . 'datedept', '' . "\0" . 'Gestion\\GestionBundle\\Entity\\Absence' . "\0" . 'dateretour', '' . "\0" . 'Gestion\\GestionBundle\\Entity\\Absence' . "\0" . 'employe', '' . "\0" . 'Gestion\\GestionBundle\\Entity\\Absence' . "\0" . 'destination', '' . "\0" . 'Gestion\\GestionBundle\\Entity\\Absence' . "\0" . 'motif');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Absence $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setDestination($destination)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDestination', array($destination));

        return parent::setDestination($destination);
    }

    /**
     * {@inheritDoc}
     */
    public function getDestination()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDestination', array());

        return parent::getDestination();
    }

    /**
     * {@inheritDoc}
     */
    public function setMotif($motif)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMotif', array($motif));

        return parent::setMotif($motif);
    }

    /**
     * {@inheritDoc}
     */
    public function getMotif()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMotif', array());

        return parent::getMotif();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmploye(\Gestion\GestionBundle\Entity\Employe $employe = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmploye', array($employe));

        return parent::setEmploye($employe);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmploye()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmploye', array());

        return parent::getEmploye();
    }

    /**
     * {@inheritDoc}
     */
    public function setDatedept($datedept)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDatedept', array($datedept));

        return parent::setDatedept($datedept);
    }

    /**
     * {@inheritDoc}
     */
    public function getDatedept()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDatedept', array());

        return parent::getDatedept();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateretour($dateretour)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateretour', array($dateretour));

        return parent::setDateretour($dateretour);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateretour()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateretour', array());

        return parent::getDateretour();
    }

}
