<?php

namespace Proxies\__CG__\Ventes\VentesBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class DetailsProduits extends \Ventes\VentesBundle\Entity\DetailsProduits implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Ventes\\VentesBundle\\Entity\\DetailsProduits' . "\0" . 'id', '' . "\0" . 'Ventes\\VentesBundle\\Entity\\DetailsProduits' . "\0" . 'idProduit', '' . "\0" . 'Ventes\\VentesBundle\\Entity\\DetailsProduits' . "\0" . 'idCategoriePoduit', '' . "\0" . 'Ventes\\VentesBundle\\Entity\\DetailsProduits' . "\0" . 'refProd', '' . "\0" . 'Ventes\\VentesBundle\\Entity\\DetailsProduits' . "\0" . 'libelle', '' . "\0" . 'Ventes\\VentesBundle\\Entity\\DetailsProduits' . "\0" . 'prixHT', '' . "\0" . 'Ventes\\VentesBundle\\Entity\\DetailsProduits' . "\0" . 'date', '' . "\0" . 'Ventes\\VentesBundle\\Entity\\DetailsProduits' . "\0" . 'quantite', '' . "\0" . 'Ventes\\VentesBundle\\Entity\\DetailsProduits' . "\0" . 'facture');
        }

        return array('__isInitialized__', '' . "\0" . 'Ventes\\VentesBundle\\Entity\\DetailsProduits' . "\0" . 'id', '' . "\0" . 'Ventes\\VentesBundle\\Entity\\DetailsProduits' . "\0" . 'idProduit', '' . "\0" . 'Ventes\\VentesBundle\\Entity\\DetailsProduits' . "\0" . 'idCategoriePoduit', '' . "\0" . 'Ventes\\VentesBundle\\Entity\\DetailsProduits' . "\0" . 'refProd', '' . "\0" . 'Ventes\\VentesBundle\\Entity\\DetailsProduits' . "\0" . 'libelle', '' . "\0" . 'Ventes\\VentesBundle\\Entity\\DetailsProduits' . "\0" . 'prixHT', '' . "\0" . 'Ventes\\VentesBundle\\Entity\\DetailsProduits' . "\0" . 'date', '' . "\0" . 'Ventes\\VentesBundle\\Entity\\DetailsProduits' . "\0" . 'quantite', '' . "\0" . 'Ventes\\VentesBundle\\Entity\\DetailsProduits' . "\0" . 'facture');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (DetailsProduits $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setRefProd($refProd)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRefProd', array($refProd));

        return parent::setRefProd($refProd);
    }

    /**
     * {@inheritDoc}
     */
    public function getRefProd()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRefProd', array());

        return parent::getRefProd();
    }

    /**
     * {@inheritDoc}
     */
    public function setLibelle($libelle)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLibelle', array($libelle));

        return parent::setLibelle($libelle);
    }

    /**
     * {@inheritDoc}
     */
    public function getLibelle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLibelle', array());

        return parent::getLibelle();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrixHT($prixHT)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrixHT', array($prixHT));

        return parent::setPrixHT($prixHT);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrixHT()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrixHT', array());

        return parent::getPrixHT();
    }

    /**
     * {@inheritDoc}
     */
    public function setQuantite($quantite)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setQuantite', array($quantite));

        return parent::setQuantite($quantite);
    }

    /**
     * {@inheritDoc}
     */
    public function getQuantite()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQuantite', array());

        return parent::getQuantite();
    }

    /**
     * {@inheritDoc}
     */
    public function setFacture(\Ventes\VentesBundle\Entity\Facture $facture)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFacture', array($facture));

        return parent::setFacture($facture);
    }

    /**
     * {@inheritDoc}
     */
    public function getFacture()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFacture', array());

        return parent::getFacture();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function setDate($date)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDate', array($date));

        return parent::setDate($date);
    }

    /**
     * {@inheritDoc}
     */
    public function getDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDate', array());

        return parent::getDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setCategorie($categorie)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCategorie', array($categorie));

        return parent::setCategorie($categorie);
    }

    /**
     * {@inheritDoc}
     */
    public function getCategorie()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCategorie', array());

        return parent::getCategorie();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdProduit($idProduit)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdProduit', array($idProduit));

        return parent::setIdProduit($idProduit);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdProduit()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdProduit', array());

        return parent::getIdProduit();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdCategorieProduit($idCategorieProduit)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdCategorieProduit', array($idCategorieProduit));

        return parent::setIdCategorieProduit($idCategorieProduit);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdCategorieProduit()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdCategorieProduit', array());

        return parent::getIdCategorieProduit();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdCategoriePoduit($idCategoriePoduit)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdCategoriePoduit', array($idCategoriePoduit));

        return parent::setIdCategoriePoduit($idCategoriePoduit);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdCategoriePoduit()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdCategoriePoduit', array());

        return parent::getIdCategoriePoduit();
    }

}
