<?php

namespace Proxies\__CG__\Gestion\GestionBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Banque extends \Gestion\GestionBundle\Entity\Banque implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Gestion\\GestionBundle\\Entity\\Banque' . "\0" . 'id', '' . "\0" . 'Gestion\\GestionBundle\\Entity\\Banque' . "\0" . 'libbanque', '' . "\0" . 'Gestion\\GestionBundle\\Entity\\Banque' . "\0" . 'salnet', '' . "\0" . 'Gestion\\GestionBundle\\Entity\\Banque' . "\0" . 'totalGain', '' . "\0" . 'Gestion\\GestionBundle\\Entity\\Banque' . "\0" . 'totalRetenue', '' . "\0" . 'Gestion\\GestionBundle\\Entity\\Banque' . "\0" . 'dated', '' . "\0" . 'Gestion\\GestionBundle\\Entity\\Banque' . "\0" . 'datef', '' . "\0" . 'Gestion\\GestionBundle\\Entity\\Banque' . "\0" . 'employe', '' . "\0" . 'Gestion\\GestionBundle\\Entity\\Banque' . "\0" . 'salairecompoTable');
        }

        return array('__isInitialized__', '' . "\0" . 'Gestion\\GestionBundle\\Entity\\Banque' . "\0" . 'id', '' . "\0" . 'Gestion\\GestionBundle\\Entity\\Banque' . "\0" . 'libbanque', '' . "\0" . 'Gestion\\GestionBundle\\Entity\\Banque' . "\0" . 'salnet', '' . "\0" . 'Gestion\\GestionBundle\\Entity\\Banque' . "\0" . 'totalGain', '' . "\0" . 'Gestion\\GestionBundle\\Entity\\Banque' . "\0" . 'totalRetenue', '' . "\0" . 'Gestion\\GestionBundle\\Entity\\Banque' . "\0" . 'dated', '' . "\0" . 'Gestion\\GestionBundle\\Entity\\Banque' . "\0" . 'datef', '' . "\0" . 'Gestion\\GestionBundle\\Entity\\Banque' . "\0" . 'employe', '' . "\0" . 'Gestion\\GestionBundle\\Entity\\Banque' . "\0" . 'salairecompoTable');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Banque $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setLibbanque($libbanque)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLibbanque', array($libbanque));

        return parent::setLibbanque($libbanque);
    }

    /**
     * {@inheritDoc}
     */
    public function getLibbanque()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLibbanque', array());

        return parent::getLibbanque();
    }

    /**
     * {@inheritDoc}
     */
    public function setSalnet($salnet)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSalnet', array($salnet));

        return parent::setSalnet($salnet);
    }

    /**
     * {@inheritDoc}
     */
    public function getSalnet()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSalnet', array());

        return parent::getSalnet();
    }

    /**
     * {@inheritDoc}
     */
    public function setTotalGain($totalGain)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTotalGain', array($totalGain));

        return parent::setTotalGain($totalGain);
    }

    /**
     * {@inheritDoc}
     */
    public function getTotalGain()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotalGain', array());

        return parent::getTotalGain();
    }

    /**
     * {@inheritDoc}
     */
    public function setTotalRetenue($totalRetenue)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTotalRetenue', array($totalRetenue));

        return parent::setTotalRetenue($totalRetenue);
    }

    /**
     * {@inheritDoc}
     */
    public function getTotalRetenue()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotalRetenue', array());

        return parent::getTotalRetenue();
    }

    /**
     * {@inheritDoc}
     */
    public function setDated($dated)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDated', array($dated));

        return parent::setDated($dated);
    }

    /**
     * {@inheritDoc}
     */
    public function getDated()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDated', array());

        return parent::getDated();
    }

    /**
     * {@inheritDoc}
     */
    public function setDatef($datef)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDatef', array($datef));

        return parent::setDatef($datef);
    }

    /**
     * {@inheritDoc}
     */
    public function getDatef()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDatef', array());

        return parent::getDatef();
    }

    /**
     * {@inheritDoc}
     */
    public function setSalairecompoTable($salairecompoTable)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSalairecompoTable', array($salairecompoTable));

        return parent::setSalairecompoTable($salairecompoTable);
    }

    /**
     * {@inheritDoc}
     */
    public function getSalairecompoTable()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSalairecompoTable', array());

        return parent::getSalairecompoTable();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmploye(\Gestion\GestionBundle\Entity\Employe $employe = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmploye', array($employe));

        return parent::setEmploye($employe);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmploye()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmploye', array());

        return parent::getEmploye();
    }

}
