<?php

namespace Ventes\VentesBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CategorieClientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieClientRepository extends EntityRepository
{
}
