<?php

namespace Ventes\VentesBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DetailsProduitsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DetailsProduitsRepository extends EntityRepository
{

}
