<?php

namespace Ventes\VentesBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EncaissementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EncaissementRepository extends EntityRepository
{
     public function ParCAApporteur($id, $datedebut, $datefin){
       $qb = $this->createQueryBuilder('e')
                ->join('e.facture', 'f')
                ->addSelect('f')  
               ->where("f.id = :id")
               ->andWhere("e.dateFormat >=:datedebut")
               ->andWhere("e.dateFormat <=:datefin")
               ->setParameter('id',$id )
               ->setParameter('datedebut', $datedebut)
               ->setParameter('datefin', $datefin );
       return $qb->getQuery()->getResult();
    }
    
    public function ParJournal($datedebut, $datefin){
           
       $qb = $this->createQueryBuilder('e')
               ->where("e.dateFormat >=:datedebut")
               ->andWhere("e.dateFormat <=:datefin")
               ->setParameter('datedebut', $datedebut)
               ->setParameter('datefin', $datefin );
       return $qb->getQuery()->getResult();
    }
}
