<?php

namespace Ventes\VentesBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * FactureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FactureRepository extends EntityRepository
{   
    public function findByTousFacture(){
            $etat = 'Proforma';

       $qb = $this->createQueryBuilder('f')
               ->where("f.etat not like :etat")
               ->orderBy('f.etat', 'ASC')
               ->setParameter('etat',$etat );
       return $qb->getQuery()->getResult();
    }
    public function ParCompte($id, $datedebut, $datefin){
       $qb = $this->createQueryBuilder('f')
                ->join('f.client', 'c')
                ->addSelect('c')  
               ->where("c.id = :id")
               ->andWhere("f.dateFacture >=:datedebut")
               ->andWhere("f.dateFacture <=:datefin")
               ->setParameter('id',$id )
               ->setParameter('datedebut', $datedebut)
               ->setParameter('datefin', $datefin );
       return $qb->getQuery()->getResult();
    }
    
}
