<?php

namespace Ventes\VentesBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * OperationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OperationRepository extends EntityRepository
{
     public function ParJournal($datedebut, $datefin){
           $nature ="Espèce";
       $qb = $this->createQueryBuilder('o')
               ->where("o.dateFormat >=:datedebut")
               ->andWhere("o.dateFormat <=:datefin")
               ->andWhere("o.nature like :nature")
               ->setParameter('datedebut', $datedebut)
               ->setParameter('datefin', $datefin )
               ->setParameter('nature', $nature );
       return $qb->getQuery()->getResult();
    }
}
