<?php

namespace Ventes\VentesBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitRepository extends EntityRepository {

    public function ParClientFiltre($client) {
        $qb = $this->createQueryBuilder('p')
                ->orderBy('p.libelle', 'ASC')
                ->where('p.client = :client')
                ->setParameter('client', $client);
        return $qb;
    }

}
