<?php

namespace Members\MembersBundle\Repository;

/**
 * AccountMemberRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccountGroupRepository extends \Doctrine\ORM\EntityRepository
{
}
